name: Git Push
version: "1.0.2"
slug: git_push
description: Push your Home Assistant configuration to a Git repository
url: https://github.com/bazza2k/HA_GitPush
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
map:
  - config:rw
options:
  git_host: ""
  git_port: 22
  git_repository: ""
  git_branch: main
  git_remote: origin
  git_user: ""
  git_email: ""
  auth_method: ssh_key
  deployment_user: ""
  deployment_password: ""
  deployment_key: []
  deployment_key_protocol: ed25519
  auto_push: false
  commit_message: "Update Home Assistant config"
  push_ignore:
    - .git/
    - .addon_data/
    - secrets.yaml
    - ip_bans.yaml
    - .HA_VERSION
    - .storage/
    - .uuid
    - home-assistant.log*
    - deps/
    - tts/
    - *.db
    - *.db-shm
    - *.db-wal
    - www/*
    - custom_components/*
    - esphome/*
    - dwains-dashboard/*
    - themes/*
    - tts/*
    - zigbee2mqtt/*.log
    - zigbee2mqtt/log/**
    - zigbee2mqtt/coordinator_backup.json
    - zigbee2mqtt/database.db.tmp
  repeat:
    active: false
    interval: 300
schema:
  git_host: str
  git_port: int
  git_repository: str
  git_branch: str
  git_remote: str
  git_user: str
  git_email: str
  auth_method: list(ssh_key|https)
  deployment_user: str
  deployment_password: password
  deployment_key:
    - str
  deployment_key_protocol: list(ed25519|rsa)
  auto_push: bool
  commit_message: str
  push_ignore:
    - str
  repeat:
    active: bool
    interval: int
image: bazza2k/git-push
